- alias: Start HomeKit
  trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
  - platform: event
    event_type: zwave.network_complete_some_dead
  action:
  - service: homekit.start
  id: 47dc33ef02174199af9c2c32f06c01cc
- alias: Refresh deconz
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay:
      seconds: 30
  - service: deconz.device_refresh
  id: 84b0349fb2fb49f7831b9d9dc504671c
- alias: turn on bolean when alarm set to armed
  trigger:
    platform: state
    entity_id: alarm_control_panel.dressyrvagen_alarm
    to: armed_away
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.testswitch
  id: c10e3f28b4344bc3964d6aa25e3c41d6
- alias: turn off bolean when alarm set to disarmed
  trigger:
    entity_id: alarm_control_panel.dressyrvagen_alarm
    from: armed_away
    platform: state
    to: disarmed
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.testswitch
  id: 9e0deb067e5d44cf8a76b41cf4da2536
- id: '1600896011901'
  alias: test
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.vsuremail
  condition:
  - condition: state
    entity_id: sensor.vsuremail
    state: Disarmed
  action:
  - type: turn_on
    device_id: 5927c8bd0b204277bce80c167ad409bd
    entity_id: light.office_shelf
    domain: light
  mode: single
